### ISSUE TITLE
Add diagrams

### ISSUE THREAD

**Issue by billy-doyle** [compat-fork/.github#1]
Willing to make the changes needed for typed-ast dep to make installable on 3.12

https://github.com/mingrammer/diagrams

**Comment by JelleZijlstra** [comment]
Thanks, looks like this is about https://github.com/mingrammer/diagrams/issues/966.

I created https://github.com/compat-fork/diagrams and we can go with that. I'd like to use the following plan:

- First make sure CI works on the forked repo. I opened https://github.com/compat-fork/diagrams/pull/1 and CI isn't running but I haven't yet figured out why.
- Update the repo with the desired compatibility changes. Could you submit a PR for this?
- Push a release to PyPI.

**Comment by JelleZijlstra** [comment]
Repo created and uploaded to PyPI! Any future issues around this project should be added to the https://github.com/compat-fork/diagrams repo.
